// =============================================================================
// ABM TOOL LIBRARY — single source of truth
// -----------------------------------------------------------------------------
// Add a category or a tool here and the hub, category pages, tool pages, and all
// cross-links (alternatives, "tools in this category") generate automatically.
//
// IMPORTANT EDITORIAL RULES (legal + SEO):
//  - All copy here is ORIGINAL Puetto editorial. Do NOT paste G2/Capterra/Reddit
//    text, star ratings, or review counts. Link out to them instead (sourceLinks).
//  - `community` is a Puetto-written synthesis ("practitioners frequently cite..."),
//    not a quote. Always pair it with a sourceLinks entry.
//  - `alternatives` are slugs of other tools in this file — they auto-interlink.
// =============================================================================

export const CATEGORIES = [
  {
    slug: 'email-automation',
    name: 'Email Automation',
    tagline: 'Cold outbound, sequencing, and deliverability tools for ABM email plays.',
    description:
      'Email automation tools run the outbound email layer of an ABM program: multi-step sequences, inbox rotation, deliverability management, and reply handling. In an account-based motion they are used to reach named contacts inside target accounts at scale, while keeping messaging personalized enough to land.',
    intro:
      'For account-based marketing, the email layer has to do two things that are in tension: operate at enough volume to reach a full buying committee across many accounts, and stay personalized and deliverable enough that messages actually arrive and get replies. The tools below are the ones practitioners most often reach for, each with a different balance of scale, deliverability control, and CRM depth.',
  },
  {
    slug: 'linkedin-automation',
    name: 'LinkedIn Automation',
    tagline: 'Connection, messaging, and engagement automation for LinkedIn-led ABM.',
    description:
      'LinkedIn automation tools handle connection requests, message sequences, and engagement on LinkedIn — the dominant channel for B2B account-based outreach. They are used to multi-thread across a buying committee and warm accounts before or alongside email.',
    intro:
      'LinkedIn is where most B2B buying committees are reachable, which makes it central to ABM. The challenge is doing it safely: LinkedIn actively limits automation, so the tools differ mainly in how they balance throughput against account-safety. (Category page — tools coming.)',
  },
  {
    slug: 'lead-sourcing',
    name: 'Lead Sourcing & Data',
    tagline: 'Contact data, enrichment, and list-building for target accounts.',
    description:
      'Lead sourcing and data tools supply the contacts and firmographic, technographic, and intent data that feed an ABM program — the raw material for building and enriching a target account list.',
    intro:
      'An ABM program is only as good as the data underneath it. These tools build and enrich the target account list with contacts, firmographics, technographics, and intent signals. (Category page — tools coming.)',
  },
  {
    slug: 'intent-data',
    name: 'Intent Data',
    tagline: 'Signals that reveal which accounts are in-market now.',
    description:
      'Intent data platforms surface which target accounts are actively researching your category, so teams can prioritize outreach by timing — a core input to account scoring.',
    intro:
      'Intent data answers the "is now the moment?" question in account scoring. These platforms detect research surges and buying signals across the web. (Category page — tools coming.)',
  },
  {
    slug: 'abm-platforms',
    name: 'ABM Platforms',
    tagline: 'End-to-end orchestration: targeting, advertising, and measurement.',
    description:
      'ABM platforms orchestrate the full account-based motion — account selection, advertising, web personalization, and measurement — in one connected system, typically sitting on top of the CRM.',
    intro:
      'ABM platforms are the orchestration layer that ties targeting, advertising, and measurement together. These are the heavyweight, full-stack options. (Category page — tools coming.)',
  },
];

// -----------------------------------------------------------------------------
// TOOLS
// -----------------------------------------------------------------------------
export const TOOLS = [

  {
    slug: 'smartlead',
    name: 'Smartlead',
    category: 'email-automation',
    website: 'https://www.smartlead.ai',
    oneLiner: 'Cold email platform built around unlimited mailboxes and deliverability, aimed at high-volume outbound.',
    whatItDoes: 'Smartlead is a cold email automation platform whose central pitch is scale without burning deliverability. It lets teams connect unlimited email accounts and rotate sends across them, runs multi-step sequences with conditional logic, and includes a unified master inbox for handling replies across all connected mailboxes. It also offers a warmup network, sub-account structures aimed at agencies, and an API. In an ABM context it is typically the engine for reaching many contacts across a target account list while keeping per-mailbox volume low enough to stay deliverable.',
    bestFor: 'Agencies and high-volume outbound teams that send across many mailboxes and need deliverability control and an API.',
    pros: ['Unlimited mailbox connections with automatic rotation.', 'Deliverability is core, not an add-on (warmup, rotation, sending controls).', 'Master inbox consolidates replies across all accounts.', 'Agency-friendly sub-accounts and a capable API.'],
    cons: ['Interface depth can be steep for first-time outbound teams.', 'It is an outbound engine, not a full CRM.', 'Heavy multi-mailbox setups need real deliverability know-how.'],
    pricing: 'Subscription tiers based on sending volume and features, with higher tiers for agencies. Verify current pricing on the vendor site.',
    community: 'Across outbound communities and review sites, practitioners frequently cite Smartlead for deliverability and unlimited-mailbox scaling, with a recurring critique around learning curve and support at high volume. Puetto synthesis — verify against the sources below.',
    features: {"multichannel":"limited","warmup":"yes","builtInData":"no","unlimitedMailboxes":"yes","crmSync":"limited"},
    priceFrom: 'From ~$39/mo',
    bestForTag: 'High-volume outbound',
    alternatives: ['instantly', 'lemlist', 'apollo-sequences'],
    sourceLinks: [{ label: 'Smartlead on G2', url: 'https://www.g2.com/products/smartlead-ai/reviews' }, { label: 'r/Emailmarketing', url: 'https://www.reddit.com/r/Emailmarketing/' }],
  },
  {
    slug: 'instantly',
    name: 'Instantly',
    category: 'email-automation',
    website: 'https://www.instantly.ai',
    oneLiner: 'Cold email and deliverability platform popular with agencies and lead-gen teams for its simplicity and built-in lead database.',
    whatItDoes: 'Instantly is a cold outbound platform combining unlimited mailbox sending, a warmup network, campaign sequencing, and a unified inbox, with an emphasis on being approachable. It bundles a built-in B2B lead database and deliverability tooling, positioning itself as a place to source, send, and manage replies in one flow. For ABM teams it is often the day-one outbound tool because it gets a multi-mailbox campaign running quickly.',
    bestFor: 'Lead-gen teams and agencies that want multi-mailbox cold email running fast, with sourcing and warmup bundled in.',
    pros: ['Fast to set up — a multi-mailbox campaign can be live quickly.', 'Large warmup network and built-in deliverability tooling.', 'Bundled lead database reduces separate tools.', 'Clean, approachable interface.'],
    cons: ['Less granular control than power-user tools.', 'Bundled lead-data quality varies by segment.', 'Results depend heavily on list and copy quality.'],
    pricing: 'Tiered subscriptions by sending volume and seats, with separate pricing for the lead database. Verify on the vendor site.',
    community: 'Practitioners often praise Instantly for ease of setup and deliverability, while recurring critiques center on lead-data quality and support at scale. Puetto synthesis — verify against the sources below.',
    features: {"multichannel":"limited","warmup":"yes","builtInData":"yes","unlimitedMailboxes":"yes","crmSync":"limited"},
    priceFrom: 'From ~$37/mo',
    bestForTag: 'Fast setup',
    alternatives: ['smartlead', 'lemlist', 'apollo-sequences'],
    sourceLinks: [{ label: 'Instantly on G2', url: 'https://www.g2.com/products/instantly/reviews' }, { label: 'r/coldemail', url: 'https://www.reddit.com/r/coldemail/' }],
  },
  {
    slug: 'lemlist',
    name: 'lemlist',
    category: 'email-automation',
    website: 'https://www.lemlist.com',
    oneLiner: 'Outbound platform known for personalization at scale: dynamic images, custom landing pages, and multichannel sequences.',
    whatItDoes: 'lemlist is an outbound sequencing platform that leans into personalization: dynamic image and text personalization, personalized landing pages, and multichannel steps that combine email with LinkedIn and calls. It includes warmup and a contact database. For ABM, its differentiator is making each touch feel bespoke even at volume, which suits account-based plays where relevance matters more than raw throughput.',
    bestFor: 'Teams that prioritize personalization and multichannel sequencing over maximum send volume.',
    pros: ['Strong personalization, including dynamic images and custom landing pages.', 'Native multichannel sequences (email + LinkedIn + calls).', 'Built-in warmup and contact database.', 'Active community and template library.'],
    cons: ['Personalization depth adds setup effort per campaign.', 'Can be pricier per seat than bare-bones senders.', 'Very high-volume many-mailbox setups are not its core focus.'],
    pricing: 'Per-seat subscription tiers, with higher tiers unlocking multichannel and advanced personalization. Verify on the vendor site.',
    community: 'Reviewers commonly highlight lemlist for personalization and multichannel flows, with critiques around price and a learning curve. Puetto synthesis — verify against the sources below.',
    features: {"multichannel":"yes","warmup":"yes","builtInData":"yes","unlimitedMailboxes":"limited","crmSync":"yes"},
    priceFrom: 'From ~$39/mo',
    bestForTag: 'Personalization',
    alternatives: ['smartlead', 'instantly', 'lemwarm'],
    sourceLinks: [{ label: 'lemlist on G2', url: 'https://www.g2.com/products/lemlist/reviews' }, { label: 'lemlist on Capterra', url: 'https://www.capterra.com/p/151730/lemlist/' }],
  },
  {
    slug: 'apollo-sequences',
    name: 'Apollo.io (Sequences)',
    category: 'email-automation',
    website: 'https://www.apollo.io',
    oneLiner: 'Combined contact database and outbound sequencing: sourcing and sending in one platform.',
    whatItDoes: 'Apollo.io pairs a large B2B contact and company database with built-in outbound sequencing, so teams can find target-account contacts and email them from the same tool. It includes enrichment, basic intent signals, and CRM-style features. For ABM, its appeal is consolidation: sourcing the buying committee and running sequences against it without exporting to a separate sender.',
    bestFor: 'Teams that want sourcing and sending in one place and prefer consolidation over best-in-class deliverability.',
    pros: ['Combines a large contact database with sequencing.', 'Built-in enrichment and basic intent data.', 'Cost-effective entry point for smaller teams.'],
    cons: ['Deliverability controls less specialized than dedicated cold-email tools.', 'Data accuracy varies by region and segment.', 'High volume from few mailboxes carries deliverability risk.'],
    pricing: 'Freemium with paid tiers by seats and credits. Verify on the vendor site.',
    community: 'Practitioners frequently value Apollo for all-in-one sourcing plus sending and price, while raising data-accuracy and deliverability caveats for heavy cold outbound. Puetto synthesis — verify against the sources below.',
    features: {"multichannel":"limited","warmup":"no","builtInData":"yes","unlimitedMailboxes":"no","crmSync":"yes"},
    priceFrom: 'Free / from ~$49/mo',
    bestForTag: 'All-in-one',
    alternatives: ['smartlead', 'instantly', 'outreach'],
    sourceLinks: [{ label: 'Apollo.io on G2', url: 'https://www.g2.com/products/apollo-io/reviews' }, { label: 'r/sales', url: 'https://www.reddit.com/r/sales/' }],
  },
  {
    slug: 'outreach',
    name: 'Outreach',
    category: 'email-automation',
    website: 'https://www.outreach.io',
    oneLiner: 'Enterprise sales engagement platform for sequencing, calling, and pipeline execution across large sales teams.',
    whatItDoes: 'Outreach is a sales engagement platform built for larger revenue teams. It runs multi-step, multichannel sequences (email, calls, LinkedIn tasks), with deep Salesforce sync, analytics, and AI-assisted features for reps and managers. In ABM it is the system reps live in to execute coordinated outreach against target accounts while marketing and ops track engagement centrally.',
    bestFor: 'Mid-market and enterprise sales teams that need governed, CRM-synced sequencing at scale, not lightweight cold email.',
    pros: ['Deep CRM (especially Salesforce) integration and reporting.', 'Multichannel sequences with task management for reps.', 'Strong analytics and team governance features.'],
    cons: ['Priced and built for larger teams, not solo senders.', 'Setup and administration require dedicated ops resource.', 'More than small teams need for pure cold email.'],
    pricing: 'Enterprise per-seat pricing, typically annual. Contact vendor for a quote.',
    community: 'Reviewers consistently rate Outreach for enterprise sequencing power and CRM depth, with critiques on cost and admin complexity. Puetto synthesis — verify against the sources below.',
    features: {"multichannel":"yes","warmup":"no","builtInData":"no","unlimitedMailboxes":"no","crmSync":"yes"},
    priceFrom: 'Enterprise (quote)',
    bestForTag: 'Enterprise sales',
    alternatives: ['salesloft', 'apollo-sequences', 'hubspot-sequences'],
    sourceLinks: [{ label: 'Outreach on G2', url: 'https://www.g2.com/products/outreach/reviews' }, { label: 'r/sales', url: 'https://www.reddit.com/r/sales/' }],
  },
  {
    slug: 'salesloft',
    name: 'Salesloft',
    category: 'email-automation',
    website: 'https://www.salesloft.com',
    oneLiner: 'Sales engagement platform centered on cadences, conversation intelligence, and revenue workflow.',
    whatItDoes: 'Salesloft is a sales engagement platform offering cadences (sequences) across email, phone, and social, plus conversation intelligence, deal management, and forecasting. It is a direct alternative to Outreach for teams standardizing rep outreach. In ABM it coordinates how reps work target-account contacts and feeds engagement data back to the CRM and reporting layer.',
    bestFor: 'Sales-led organizations wanting cadences plus conversation intelligence and forecasting in one platform.',
    pros: ['Mature cadence engine with multichannel steps.', 'Built-in conversation intelligence and deal tooling.', 'Strong CRM integration and analytics.'],
    cons: ['Enterprise pricing and onboarding overhead.', 'Overkill for small teams or pure cold email.', 'Requires ops ownership to run well.'],
    pricing: 'Enterprise per-seat pricing, typically annual. Contact vendor for a quote.',
    community: 'Practitioners rate Salesloft highly for cadence management and conversation intelligence, with cost and complexity as common caveats. Puetto synthesis — verify against the sources below.',
    features: {"multichannel":"yes","warmup":"no","builtInData":"no","unlimitedMailboxes":"no","crmSync":"yes"},
    priceFrom: 'Enterprise (quote)',
    bestForTag: 'Cadences + CI',
    alternatives: ['outreach', 'apollo-sequences', 'hubspot-sequences'],
    sourceLinks: [{ label: 'Salesloft on G2', url: 'https://www.g2.com/products/salesloft/reviews' }, { label: 'Salesloft on Capterra', url: 'https://www.capterra.com/p/154633/SalesLoft/' }],
  },
  {
    slug: 'hubspot-sequences',
    name: 'HubSpot Sales (Sequences)',
    category: 'email-automation',
    website: 'https://www.hubspot.com/products/sales',
    oneLiner: 'Email sequencing and sales automation native to the HubSpot CRM.',
    whatItDoes: 'HubSpot Sales Hub includes Sequences — automated, personalized email follow-ups with task steps — running directly inside the HubSpot CRM. Because it shares the same contact and account records as marketing and service, engagement is unified. For ABM teams already on HubSpot, it is the path of least resistance for one-to-one and one-to-few outreach with full CRM context.',
    bestFor: 'Teams already on HubSpot that want sequencing without adding a separate sales-engagement tool.',
    pros: ['Native to the HubSpot CRM — no integration gap.', 'Shared records across marketing, sales, and service.', 'Approachable for teams already in HubSpot.'],
    cons: ['Sending volume and enrollment limits per tier.', 'Less specialized for high-volume cold outbound.', 'Best value only if you are already on HubSpot.'],
    pricing: 'Included in paid Sales Hub tiers; scales with seats and features. Verify on the vendor site.',
    community: 'HubSpot users value Sequences for CRM-native convenience, with limits on volume and cold-outbound depth as common notes. Puetto synthesis — verify against the sources below.',
    features: {"multichannel":"limited","warmup":"no","builtInData":"limited","unlimitedMailboxes":"no","crmSync":"yes"},
    priceFrom: 'Paid Sales Hub tiers',
    bestForTag: 'HubSpot teams',
    alternatives: ['outreach', 'salesloft', 'apollo-sequences'],
    sourceLinks: [{ label: 'HubSpot Sales on G2', url: 'https://www.g2.com/products/hubspot-sales-hub/reviews' }],
  },
  {
    slug: 'reply-io',
    name: 'Reply.io',
    category: 'email-automation',
    website: 'https://reply.io',
    oneLiner: 'Multichannel sales engagement and AI-assisted outbound across email, LinkedIn, calls, and SMS.',
    whatItDoes: 'Reply.io is a sales engagement platform combining multichannel sequencing (email, LinkedIn, calls, SMS, WhatsApp), AI features for drafting and responding, and a contact database. It targets teams wanting outbound automation across channels without enterprise complexity. In ABM it supports multi-threaded outreach to a buying committee across more than just email.',
    bestFor: 'SMB and mid-market teams wanting multichannel sequencing with AI assistance at a moderate price.',
    pros: ['True multichannel sequences beyond email.', 'AI features for drafting and reply handling.', 'Built-in data and integrations.'],
    cons: ['Breadth can mean less depth in any single channel.', 'Deliverability tooling lighter than cold-email specialists.', 'AI output still needs human editing.'],
    pricing: 'Tiered per-seat pricing with data add-ons. Verify on the vendor site.',
    community: 'Reviewers value Reply.io for multichannel breadth and AI assistance, with notes on per-channel depth and data quality. Puetto synthesis — verify against the sources below.',
    features: {"multichannel":"yes","warmup":"yes","builtInData":"yes","unlimitedMailboxes":"limited","crmSync":"yes"},
    priceFrom: 'From ~$59/mo',
    bestForTag: 'Multichannel + AI',
    alternatives: ['lemlist', 'smartlead', 'instantly'],
    sourceLinks: [{ label: 'Reply.io on G2', url: 'https://www.g2.com/products/reply/reviews' }],
  },
  {
    slug: 'woodpecker',
    name: 'Woodpecker',
    category: 'email-automation',
    website: 'https://woodpecker.co',
    oneLiner: 'Cold email tool focused on deliverability and a human-like sending approach, popular with agencies.',
    whatItDoes: 'Woodpecker is a cold email platform emphasizing deliverability and sending that mimics human behavior, with automatic follow-ups, condition-based campaigns, inbox rotation, and an agency panel. It targets B2B teams and agencies that want reliable inbox placement without an enterprise sales-engagement stack. For ABM it handles the email layer with a deliverability-first posture.',
    bestFor: 'Agencies and B2B teams that prioritize deliverability and a straightforward cold-email workflow.',
    pros: ['Deliverability-first design with inbox rotation.', 'Agency panel for managing multiple clients.', 'Condition-based campaign logic.'],
    cons: ['Less of an all-in-one than larger platforms.', 'Native data/sourcing is limited.', 'Multichannel is not the core focus.'],
    pricing: 'Tiered by contacted prospects and slots, with agency options. Verify on the vendor site.',
    community: 'Practitioners cite Woodpecker for deliverability and agency features, with critiques on breadth versus all-in-one tools. Puetto synthesis — verify against the sources below.',
    features: {"multichannel":"limited","warmup":"yes","builtInData":"no","unlimitedMailboxes":"limited","crmSync":"limited"},
    priceFrom: 'From ~$29/mo',
    bestForTag: 'Deliverability',
    alternatives: ['smartlead', 'instantly', 'mailshake'],
    sourceLinks: [{ label: 'Woodpecker on G2', url: 'https://www.g2.com/products/woodpecker-co/reviews' }],
  },
  {
    slug: 'mailshake',
    name: 'Mailshake',
    category: 'email-automation',
    website: 'https://mailshake.com',
    oneLiner: 'Approachable cold email and sales engagement tool aimed at simplicity for SMB outbound.',
    whatItDoes: 'Mailshake is a sales engagement platform for cold email with phone and social steps, built around ease of use. It offers sequences, mail-merge personalization, lead catcher for replies, and basic deliverability tooling. For smaller ABM teams it covers the email layer without a steep learning curve.',
    bestFor: 'SMB teams and founders wanting simple, affordable cold outbound without complexity.',
    pros: ['Simple, fast to learn.', 'Email plus phone and social steps.', 'Lead catcher centralizes replies.'],
    cons: ['Fewer advanced controls than power-user tools.', 'Lighter deliverability tooling at high volume.', 'Limited native data.'],
    pricing: 'Per-seat tiers. Verify on the vendor site.',
    community: 'Users praise Mailshake for simplicity and value, with critiques around depth at scale. Puetto synthesis — verify against the sources below.',
    features: {"multichannel":"limited","warmup":"limited","builtInData":"no","unlimitedMailboxes":"no","crmSync":"limited"},
    priceFrom: 'From ~$49/mo',
    bestForTag: 'SMB simplicity',
    alternatives: ['woodpecker', 'instantly', 'lemlist'],
    sourceLinks: [{ label: 'Mailshake on G2', url: 'https://www.g2.com/products/mailshake/reviews' }],
  },
  {
    slug: 'lemwarm',
    name: 'lemwarm / lemlist warmup',
    category: 'email-automation',
    website: 'https://www.lemlist.com/lemwarm',
    oneLiner: 'Email warmup and deliverability monitoring, originally built alongside lemlist.',
    whatItDoes: 'lemwarm is a deliverability and email warmup product that gradually builds sender reputation by simulating natural email activity, and monitors placement across providers. It is used to keep cold-email domains out of spam. In ABM it protects the deliverability of the mailboxes your sequences run from, which is foundational to any volume play.',
    bestFor: 'Teams running cold email that need dedicated warmup and deliverability monitoring for their sending domains.',
    pros: ['Dedicated warmup and reputation building.', 'Deliverability monitoring across providers.', 'Integrates with the lemlist ecosystem.'],
    cons: ['A point tool, not a full sender.', 'Most valuable paired with a sending platform.', 'Warmup is necessary but not sufficient for inbox placement.'],
    pricing: 'Subscription, sometimes bundled with lemlist plans. Verify on the vendor site.',
    community: 'Practitioners treat warmup tools like lemwarm as table stakes for cold email, debating how much warmup alone moves placement. Puetto synthesis — verify against the sources below.',
    features: {"multichannel":"no","warmup":"yes","builtInData":"no","unlimitedMailboxes":"no","crmSync":"no"},
    priceFrom: 'From ~$29/mo',
    bestForTag: 'Warmup layer',
    alternatives: ['smartlead', 'instantly', 'lemlist'],
    sourceLinks: [{ label: 'lemlist on G2', url: 'https://www.g2.com/products/lemlist/reviews' }],
  },
  {
    slug: 'mailreach',
    name: 'MailReach',
    category: 'email-automation',
    website: 'https://www.mailreach.co',
    oneLiner: 'Email warmup and deliverability tool that builds and monitors sender reputation.',
    whatItDoes: 'MailReach is a deliverability product focused on warming up mailboxes and monitoring inbox placement and spam-score health. It runs automated warmup conversations and provides reputation reporting. For ABM senders, it sits underneath the sending layer to keep domains landing in the inbox.',
    bestFor: 'Cold-email teams wanting a standalone warmup and deliverability monitor independent of their sender.',
    pros: ['Automated warmup with placement reporting.', 'Works alongside most senders.', 'Spam-score and reputation diagnostics.'],
    cons: ['A point tool, not a sender.', 'Warmup is one factor among many in deliverability.', 'Adds another subscription to the stack.'],
    pricing: 'Per-mailbox subscription. Verify on the vendor site.',
    community: 'Reviewers value MailReach as a focused deliverability layer, with the usual caveat that warmup is necessary but not the whole picture. Puetto synthesis — verify against the sources below.',
    features: {"multichannel":"no","warmup":"yes","builtInData":"no","unlimitedMailboxes":"no","crmSync":"no"},
    priceFrom: 'From ~$25/mailbox',
    bestForTag: 'Warmup layer',
    alternatives: ['lemwarm', 'smartlead', 'instantly'],
    sourceLinks: [{ label: 'MailReach on G2', url: 'https://www.g2.com/products/mailreach/reviews' }],
  },
  {
    slug: 'saleshandy',
    name: 'Saleshandy',
    category: 'email-automation',
    website: 'https://www.saleshandy.com',
    oneLiner: 'Cold email outreach platform with sequencing, a lead database, and deliverability tooling.',
    whatItDoes: 'Saleshandy is a cold email platform offering multi-step sequences, unlimited email accounts on higher tiers, a built-in B2B lead finder, and deliverability features like warmup and rotation. It positions as an affordable all-in-one for outbound. In ABM it sources and sends against target-account contacts in one tool.',
    bestFor: 'Budget-conscious teams wanting sourcing plus sending and deliverability in one affordable platform.',
    pros: ['Sequencing plus a built-in lead finder.', 'Warmup and rotation included.', 'Competitive pricing.'],
    cons: ['Lead-data depth varies by region.', 'Fewer enterprise governance features.', 'Best for SMB-scale outbound.'],
    pricing: 'Tiered subscriptions by accounts and prospects. Verify on the vendor site.',
    community: 'Users cite Saleshandy for value and all-in-one convenience, with data-quality caveats. Puetto synthesis — verify against the sources below.',
    features: {"multichannel":"limited","warmup":"yes","builtInData":"yes","unlimitedMailboxes":"yes","crmSync":"limited"},
    priceFrom: 'From ~$25/mo',
    bestForTag: 'Budget all-in-one',
    alternatives: ['smartlead', 'instantly', 'apollo-sequences'],
    sourceLinks: [{ label: 'Saleshandy on G2', url: 'https://www.g2.com/products/saleshandy/reviews' }],
  },
  {
    slug: 'gmass',
    name: 'GMass',
    category: 'email-automation',
    website: 'https://www.gmass.co',
    oneLiner: 'Cold email and mail-merge tool that runs entirely inside Gmail.',
    whatItDoes: 'GMass is a Gmail-based mass-email and cold-outreach tool offering mail merge, automated follow-ups, scheduling, and basic analytics without leaving the inbox. It suits teams that want to send sequences from Gmail directly. For lean ABM motions it is a low-friction way to run personalized outreach from existing Google Workspace accounts.',
    bestFor: 'Solo operators and small teams that want to send sequences directly from Gmail.',
    pros: ['Runs natively in Gmail — minimal learning curve.', 'Mail merge and automated follow-ups.', 'Inexpensive entry point.'],
    cons: ['Tied to Gmail sending limits.', 'Lighter on deliverability tooling for scale.', 'Not built for many-mailbox rotation.'],
    pricing: 'Low-cost per-user subscription tiers. Verify on the vendor site.',
    community: 'Reviewers like GMass for simplicity inside Gmail, noting it is best for modest volume. Puetto synthesis — verify against the sources below.',
    features: {"multichannel":"no","warmup":"limited","builtInData":"no","unlimitedMailboxes":"no","crmSync":"limited"},
    priceFrom: 'From ~$25/mo',
    bestForTag: 'Gmail-native',
    alternatives: ['mailshake', 'instantly', 'smartlead'],
    sourceLinks: [{ label: 'GMass on G2', url: 'https://www.g2.com/products/gmass/reviews' }],
  },
  {
    slug: 'klenty',
    name: 'Klenty',
    category: 'email-automation',
    website: 'https://www.klenty.com',
    oneLiner: 'Sales engagement platform with multichannel cadences and CRM-focused workflows.',
    whatItDoes: 'Klenty is a sales engagement platform offering multichannel cadences (email, calls, LinkedIn, SMS), CRM integrations, and routing/automation for SDR teams. It aims to give mid-market sales teams sequencing power without enterprise overhead. In ABM it coordinates rep outreach across channels against target accounts.',
    bestFor: 'Mid-market SDR teams wanting multichannel cadences and CRM workflows at a moderate price.',
    pros: ['Multichannel cadences with CRM sync.', 'Routing and automation for SDR workflows.', 'More affordable than top-tier enterprise tools.'],
    cons: ['Less brand recognition than Outreach/Salesloft.', 'Deliverability tooling lighter than cold-email specialists.', 'Some depth trade-offs across channels.'],
    pricing: 'Per-seat tiers. Verify on the vendor site.',
    community: 'Practitioners rate Klenty for multichannel cadences and value relative to enterprise tools. Puetto synthesis — verify against the sources below.',
    features: {"multichannel":"yes","warmup":"no","builtInData":"no","unlimitedMailboxes":"no","crmSync":"yes"},
    priceFrom: 'From ~$50/seat',
    bestForTag: 'Mid-market cadences',
    alternatives: ['outreach', 'salesloft', 'reply-io'],
    sourceLinks: [{ label: 'Klenty on G2', url: 'https://www.g2.com/products/klenty/reviews' }],
  },
  {
    slug: 'snov-io',
    name: 'Snov.io',
    category: 'email-automation',
    website: 'https://snov.io',
    oneLiner: 'Email finder, verifier, and cold-outreach platform combining data and sending.',
    whatItDoes: 'Snov.io combines a B2B email finder and verifier with drip campaigns and a small CRM. Teams can source and verify contacts, then run automated email sequences from the same tool. In ABM it covers sourcing and sending for smaller programs that want both in one place.',
    bestFor: 'SMB teams wanting email finding, verification, and sending bundled affordably.',
    pros: ['Email finder and verifier plus sending.', 'Built-in lightweight CRM.', 'Credit-based, budget-friendly.'],
    cons: ['Data coverage varies by region.', 'Lighter deliverability tooling at scale.', 'Not built for enterprise governance.'],
    pricing: 'Credit-based tiers. Verify on the vendor site.',
    community: 'Users value Snov.io for combining finding, verifying, and sending at low cost, with data-coverage caveats. Puetto synthesis — verify against the sources below.',
    features: {"multichannel":"limited","warmup":"yes","builtInData":"yes","unlimitedMailboxes":"limited","crmSync":"limited"},
    priceFrom: 'From ~$30/mo',
    bestForTag: 'Find + send',
    alternatives: ['apollo-sequences', 'saleshandy', 'instantly'],
    sourceLinks: [{ label: 'Snov.io on G2', url: 'https://www.g2.com/products/snov-io/reviews' }],
  },
  {
    slug: 'quickmail',
    name: 'QuickMail',
    category: 'email-automation',
    website: 'https://quickmail.com',
    oneLiner: 'Cold email automation with strong deliverability features and agency support.',
    whatItDoes: 'QuickMail is a cold email platform focused on deliverability, inbox rotation, automated follow-ups, and an agency-friendly structure, with its own deliverability monitoring product. It targets teams running sustained outbound that need reliable placement. For ABM it handles the email layer with a deliverability emphasis similar to Woodpecker and Smartlead.',
    bestFor: 'Agencies and teams running ongoing outbound that prioritize deliverability and inbox rotation.',
    pros: ['Deliverability-focused with inbox rotation.', 'Agency features and reporting.', 'Companion deliverability monitoring.'],
    cons: ['Native data is limited.', 'Less of an all-in-one than larger platforms.', 'Multichannel is secondary.'],
    pricing: 'Tiered by mailboxes/volume, with agency options. Verify on the vendor site.',
    community: 'Practitioners cite QuickMail for deliverability and agency support, with breadth as the trade-off. Puetto synthesis — verify against the sources below.',
    features: {"multichannel":"limited","warmup":"yes","builtInData":"no","unlimitedMailboxes":"limited","crmSync":"limited"},
    priceFrom: 'From ~$49/mo',
    bestForTag: 'Deliverability',
    alternatives: ['woodpecker', 'smartlead', 'mailshake'],
    sourceLinks: [{ label: 'QuickMail on G2', url: 'https://www.g2.com/products/quickmail/reviews' }],
  },
  {
    slug: 'mailmeteor',
    name: 'Mailmeteor',
    category: 'email-automation',
    website: 'https://mailmeteor.com',
    oneLiner: 'Privacy-focused mail-merge and email campaign tool for Gmail and Google Sheets.',
    whatItDoes: 'Mailmeteor is a mail-merge tool that sends personalized email campaigns from Gmail using Google Sheets as the data source, with tracking, templates, and follow-ups. It emphasizes simplicity and privacy. For lean ABM outreach it is a quick way to send personalized one-to-few campaigns from existing Google accounts.',
    bestFor: 'Small teams running personalized mail-merge campaigns from Gmail and Sheets.',
    pros: ['Simple Gmail and Sheets workflow.', 'Privacy-focused positioning.', 'Affordable and quick to start.'],
    cons: ['Tied to Gmail sending limits.', 'Not built for high-volume rotation.', 'Light on advanced sequencing.'],
    pricing: 'Low-cost subscription tiers. Verify on the vendor site.',
    community: 'Users like Mailmeteor for simple Gmail mail-merge and privacy stance, noting modest scale. Puetto synthesis — verify against the sources below.',
    features: {"multichannel":"no","warmup":"no","builtInData":"no","unlimitedMailboxes":"no","crmSync":"no"},
    priceFrom: 'From ~$10/mo',
    bestForTag: 'Gmail mail-merge',
    alternatives: ['gmass', 'mailshake', 'instantly'],
    sourceLinks: [{ label: 'Mailmeteor on G2', url: 'https://www.g2.com/products/mailmeteor/reviews' }],
  },
  {
    slug: 'mixmax',
    name: 'Mixmax',
    category: 'email-automation',
    website: 'https://www.mixmax.com',
    oneLiner: 'Gmail-based sales engagement with sequences, scheduling, and engagement tracking.',
    whatItDoes: 'Mixmax is a sales engagement tool layered on Gmail/Google Workspace, offering sequences, one-click scheduling, templates, polls/surveys in email, and engagement tracking, with CRM integrations. For ABM teams on Google Workspace it adds sequencing and meeting-booking to the inbox they already use.',
    bestFor: 'Google Workspace sales teams wanting sequencing and scheduling inside Gmail.',
    pros: ['Deep Gmail integration with rich email elements.', 'Built-in scheduling and engagement tracking.', 'CRM integrations.'],
    cons: ['Tied to the Google ecosystem.', 'Less suited to many-mailbox cold volume.', 'Higher tiers needed for full features.'],
    pricing: 'Per-seat tiers. Verify on the vendor site.',
    community: 'Reviewers value Mixmax for Gmail-native sequencing and scheduling, noting it fits warm/SDR motions more than mass cold email. Puetto synthesis — verify against the sources below.',
    features: {"multichannel":"limited","warmup":"no","builtInData":"no","unlimitedMailboxes":"no","crmSync":"yes"},
    priceFrom: 'From ~$34/seat',
    bestForTag: 'Gmail + scheduling',
    alternatives: ['hubspot-sequences', 'mailshake', 'klenty'],
    sourceLinks: [{ label: 'Mixmax on G2', url: 'https://www.g2.com/products/mixmax/reviews' }],
  },
  {
    slug: 'yesware',
    name: 'Yesware',
    category: 'email-automation',
    website: 'https://www.yesware.com',
    oneLiner: 'Email tracking and outreach toolkit embedded in Gmail and Outlook.',
    whatItDoes: 'Yesware adds email tracking, templates, campaigns, and meeting scheduling inside Gmail and Outlook, with CRM sync and reporting. It targets sellers who want engagement insight and light sequencing without leaving their inbox. For ABM it supports one-to-one and one-to-few outreach with tracking.',
    bestFor: 'Individual sellers and small teams in Gmail or Outlook wanting tracking and light sequencing.',
    pros: ['Works in both Gmail and Outlook.', 'Tracking, templates, and scheduling.', 'CRM sync and reporting.'],
    cons: ['Lighter on high-volume cold-email tooling.', 'Less robust than dedicated engagement platforms.', 'Best for warm/SDR-style outreach.'],
    pricing: 'Per-seat tiers, with a free option. Verify on the vendor site.',
    community: 'Users cite Yesware for inbox-native tracking and ease, with limits at high volume. Puetto synthesis — verify against the sources below.',
    features: {"multichannel":"limited","warmup":"no","builtInData":"no","unlimitedMailboxes":"no","crmSync":"yes"},
    priceFrom: 'Free / from ~$19/seat',
    bestForTag: 'Inbox tracking',
    alternatives: ['mixmax', 'hubspot-sequences', 'mailshake'],
    sourceLinks: [{ label: 'Yesware on G2', url: 'https://www.g2.com/products/yesware/reviews' }],
  },
  {
    slug: 'gong-engage',
    name: 'Gong Engage',
    category: 'email-automation',
    website: 'https://www.gong.io/engage/',
    oneLiner: 'Sales engagement built on top of Gong\u2019s revenue intelligence and conversation data.',
    whatItDoes: 'Gong Engage is the sales engagement layer of the Gong platform, running sequences and prioritized actions informed by Gong\u2019s conversation and deal intelligence. It targets teams already using Gong that want outreach guided by signal rather than guesswork. In ABM it ties rep activity on target accounts to the intelligence Gong captures from calls and emails.',
    bestFor: 'Revenue teams already on Gong wanting engagement driven by conversation and deal data.',
    pros: ['Outreach informed by Gong\u2019s intelligence.', 'Unified with conversation and deal data.', 'Prioritized actions for reps.'],
    cons: ['Most valuable only if you already use Gong.', 'Enterprise pricing.', 'Newer than dedicated engagement incumbents.'],
    pricing: 'Enterprise pricing, typically bundled with Gong. Contact vendor.',
    community: 'Practitioners see Gong Engage as compelling for existing Gong customers, with the caveat that value depends on that ecosystem. Puetto synthesis — verify against the sources below.',
    features: {"multichannel":"yes","warmup":"no","builtInData":"no","unlimitedMailboxes":"no","crmSync":"yes"},
    priceFrom: 'Enterprise (quote)',
    bestForTag: 'Gong customers',
    alternatives: ['outreach', 'salesloft', 'klenty'],
    sourceLinks: [{ label: 'Gong on G2', url: 'https://www.g2.com/products/gong/reviews' }],
  },
  {
    slug: 'amplemarket',
    name: 'Amplemarket',
    category: 'email-automation',
    website: 'https://www.amplemarket.com',
    oneLiner: 'AI-powered sales platform combining data, multichannel outreach, and deliverability.',
    whatItDoes: 'Amplemarket is an all-in-one sales platform pairing a contact database and intent signals with multichannel sequencing and built-in deliverability tooling, plus AI features for personalization and copy. It targets teams wanting sourcing, sending, and signal in one AI-assisted system. In ABM it covers data through send for target accounts.',
    bestFor: 'Teams wanting an AI-driven, all-in-one of data plus multichannel outreach plus deliverability.',
    pros: ['Combines data, intent, and multichannel sending.', 'AI personalization and copy assistance.', 'Built-in deliverability features.'],
    cons: ['Broad scope can dilute depth in places.', 'Pricing aimed at funded teams.', 'AI output needs review.'],
    pricing: 'Custom/seat-based pricing. Contact vendor.',
    community: 'Reviewers cite Amplemarket for all-in-one breadth and AI features, with cost and depth trade-offs. Puetto synthesis — verify against the sources below.',
    features: {"multichannel":"yes","warmup":"yes","builtInData":"yes","unlimitedMailboxes":"limited","crmSync":"yes"},
    priceFrom: 'Custom (quote)',
    bestForTag: 'AI all-in-one',
    alternatives: ['apollo-sequences', 'reply-io', 'smartlead'],
    sourceLinks: [{ label: 'Amplemarket on G2', url: 'https://www.g2.com/products/amplemarket/reviews' }],
  },
  {
    slug: 'la-growth-machine',
    name: 'La Growth Machine',
    category: 'email-automation',
    website: 'https://lagrowthmachine.com',
    oneLiner: 'Multichannel outreach automation across LinkedIn, email, and Twitter with enrichment.',
    whatItDoes: 'La Growth Machine automates multichannel sequences spanning LinkedIn, email, and X (Twitter), with built-in enrichment and a visual campaign builder. It emphasizes blending channels in one cadence. For ABM it multi-threads target-account contacts across the channels where they are reachable, not just email.',
    bestFor: 'Teams that want LinkedIn-plus-email multichannel sequences with enrichment in one builder.',
    pros: ['Genuine multichannel (LinkedIn + email + X).', 'Built-in enrichment.', 'Visual, flexible campaign builder.'],
    cons: ['LinkedIn automation carries account-safety considerations.', 'Email-only senders may not need the breadth.', 'Per-seat cost adds up across a team.'],
    pricing: 'Per-seat tiers by channels/identities. Verify on the vendor site.',
    community: 'Practitioners like La Growth Machine for multichannel blending and enrichment, with LinkedIn-safety as the usual caution. Puetto synthesis — verify against the sources below.',
    features: {"multichannel":"yes","warmup":"no","builtInData":"yes","unlimitedMailboxes":"no","crmSync":"limited"},
    priceFrom: 'From ~$60/seat',
    bestForTag: 'LinkedIn + email',
    alternatives: ['lemlist', 'reply-io', 'instantly'],
    sourceLinks: [{ label: 'La Growth Machine on G2', url: 'https://www.g2.com/products/la-growth-machine/reviews' }],
  },
  {
    slug: 'overloop',
    name: 'Overloop',
    category: 'email-automation',
    website: 'https://overloop.com',
    oneLiner: 'Outbound sales CRM combining prospecting, multichannel campaigns, and pipeline.',
    whatItDoes: 'Overloop (formerly Prospect.io) is an outbound-focused sales CRM with email finding, multichannel campaigns (email and LinkedIn tasks), and pipeline management in one tool. It targets small sales teams wanting prospecting and outreach without separate systems. In ABM it sources and works target accounts inside a lightweight CRM.',
    bestFor: 'Small outbound teams wanting prospecting, campaigns, and a CRM in one tool.',
    pros: ['Outbound CRM with built-in prospecting.', 'Multichannel campaign steps.', 'Pipeline management included.'],
    cons: ['Smaller ecosystem and integrations.', 'Data coverage varies.', 'Less suited to high cold-email volume.'],
    pricing: 'Per-seat tiers, sometimes credit-based. Verify on the vendor site.',
    community: 'Users value Overloop for combining CRM and outbound for small teams, with ecosystem-size caveats. Puetto synthesis — verify against the sources below.',
    features: {"multichannel":"yes","warmup":"no","builtInData":"yes","unlimitedMailboxes":"no","crmSync":"yes"},
    priceFrom: 'From ~$58/seat',
    bestForTag: 'Outbound CRM',
    alternatives: ['snov-io', 'apollo-sequences', 'klenty'],
    sourceLinks: [{ label: 'Overloop on G2', url: 'https://www.g2.com/products/overloop/reviews' }],
  },
  {
    slug: 'hunter-campaigns',
    name: 'Hunter Campaigns',
    category: 'email-automation',
    website: 'https://hunter.io',
    oneLiner: 'Email finding and verification with built-in cold email campaigns.',
    whatItDoes: 'Hunter is best known for email finding and verification, and its Campaigns feature adds simple cold-email sequences with follow-ups on top of that data. Teams can find, verify, and email from one place. For lighter ABM motions it covers sourcing and sending without a separate platform.',
    bestFor: 'Teams already using Hunter for finding/verifying who want simple sequences on top.',
    pros: ['Strong email finder and verifier.', 'Campaigns built on the same data.', 'Simple to operate.'],
    cons: ['Campaign features are basic versus dedicated senders.', 'Limited multichannel.', 'Volume better suited to SMB.'],
    pricing: 'Credit-based tiers, with a free option. Verify on the vendor site.',
    community: 'Reviewers rate Hunter highly for finding/verification, viewing Campaigns as a convenient add-on rather than a full engagement platform. Puetto synthesis — verify against the sources below.',
    features: {"multichannel":"no","warmup":"no","builtInData":"yes","unlimitedMailboxes":"no","crmSync":"limited"},
    priceFrom: 'Free / from ~$34/mo',
    bestForTag: 'Find + verify',
    alternatives: ['snov-io', 'mailshake', 'instantly'],
    sourceLinks: [{ label: 'Hunter on G2', url: 'https://www.g2.com/products/hunter/reviews' }],
  },
  {
    slug: 'clay-outbound',
    name: 'Clay (outbound)',
    category: 'email-automation',
    website: 'https://www.clay.com',
    oneLiner: 'Data orchestration and enrichment that powers highly personalized outbound at scale.',
    whatItDoes: 'Clay is a data-orchestration platform that pulls from many enrichment sources and uses AI to research accounts and contacts, then feeds personalized variables into sequencing tools or sends via integrations. It is less a sender than the personalization engine behind one. For ABM it enables research-driven, per-account personalization at a scale manual work cannot match.',
    bestFor: 'Teams that want deeply personalized outbound driven by automated research and enrichment.',
    pros: ['Aggregates many data sources in one workflow.', 'AI research enables per-account personalization.', 'Feeds most sequencing tools.'],
    cons: ['Steeper learning curve; it is a builder.', 'Often paired with a separate sender.', 'Credit costs scale with enrichment depth.'],
    pricing: 'Credit-based tiers. Verify on the vendor site.',
    community: 'Practitioners increasingly cite Clay as the personalization layer behind modern outbound, with learning curve and credit cost as the trade-offs. Puetto synthesis — verify against the sources below.',
    features: {"multichannel":"limited","warmup":"no","builtInData":"yes","unlimitedMailboxes":"no","crmSync":"yes"},
    priceFrom: 'From ~$149/mo',
    bestForTag: 'Personalization engine',
    alternatives: ['smartlead', 'lemlist', 'amplemarket'],
    sourceLinks: [{ label: 'Clay on G2', url: 'https://www.g2.com/products/clay/reviews' }, { label: 'r/coldemail', url: 'https://www.reddit.com/r/coldemail/' }],
  },
  {
    slug: 'mailchimp',
    name: 'Mailchimp',
    category: 'email-automation',
    website: 'https://mailchimp.com',
    oneLiner: 'Marketing email and automation platform for newsletters and nurture, not cold outbound.',
    whatItDoes: 'Mailchimp is a marketing-email and automation platform for opt-in newsletters, nurture journeys, and basic CRM, with templates and reporting. It is built for permission-based marketing, not cold outbound. In ABM it can run nurture and content distribution to known, opted-in contacts within target accounts rather than first-touch prospecting.',
    bestFor: 'Marketing nurture and newsletters to opted-in contacts, not cold prospecting.',
    pros: ['Mature marketing automation and templates.', 'Strong reporting and audience tools.', 'Approachable for marketers.'],
    cons: ['Not for cold outbound — permission-based only.', 'Limited fit for SDR-style sequencing.', 'Account-level ABM features are not its focus.'],
    pricing: 'Tiered by contacts and features, with a free tier. Verify on the vendor site.',
    community: 'Marketers rate Mailchimp for nurture and newsletters, noting it is the wrong tool for cold prospecting. Puetto synthesis — verify against the sources below.',
    features: {"multichannel":"limited","warmup":"no","builtInData":"no","unlimitedMailboxes":"no","crmSync":"limited"},
    priceFrom: 'Free / from ~$13/mo',
    bestForTag: 'Opt-in nurture',
    alternatives: ['hubspot-sequences', 'instantly', 'reply-io'],
    sourceLinks: [{ label: 'Mailchimp on G2', url: 'https://www.g2.com/products/mailchimp/reviews' }],
  },
  {
    slug: 'pipl-ai',
    name: 'Pipl.ai',
    category: 'email-automation',
    website: 'https://pipl.ai',
    oneLiner: 'AI cold email outreach with unlimited mailboxes, warmup, and personalization.',
    whatItDoes: 'Pipl.ai is a cold-email automation tool offering unlimited connected mailboxes, built-in warmup, AI personalization and sequence assistance, and deliverability features. It positions as an affordable scale-and-deliverability option similar to Smartlead and Instantly. In ABM it serves as a volume-capable sending layer with AI help on copy.',
    bestFor: 'Teams wanting unlimited mailboxes and AI-assisted cold email at a competitive price.',
    pros: ['Unlimited mailboxes with warmup.', 'AI personalization and sequence help.', 'Competitive pricing.'],
    cons: ['Younger product than established incumbents.', 'AI output needs human review.', 'Data/sourcing depth varies.'],
    pricing: 'Tiered subscriptions. Verify on the vendor site.',
    community: 'Early reviewers cite Pipl.ai for unlimited-mailbox value and AI features, with maturity as the watch-item. Puetto synthesis — verify against the sources below.',
    features: {"multichannel":"limited","warmup":"yes","builtInData":"limited","unlimitedMailboxes":"yes","crmSync":"limited"},
    priceFrom: 'From ~$37/mo',
    bestForTag: 'AI + unlimited inboxes',
    alternatives: ['smartlead', 'instantly', 'saleshandy'],
    sourceLinks: [{ label: 'Pipl.ai on G2', url: 'https://www.g2.com/products/pipl-ai/reviews' }],
  },
  {
    slug: 'salesforce-sales-engagement',
    name: 'Salesforce Sales Engagement',
    category: 'email-automation',
    website: 'https://www.salesforce.com/sales/engagement-platform/',
    oneLiner: 'Native cadence and sequencing inside Salesforce for teams standardizing on the platform.',
    whatItDoes: 'Salesforce Sales Engagement (formerly High Velocity Sales) provides cadences, email templates, and prioritized work queues natively within Salesforce, so reps execute outreach where the CRM already lives. For ABM teams committed to Salesforce, it keeps sequencing, activity, and account data unified without a third-party engagement tool.',
    bestFor: 'Salesforce-committed teams wanting native cadences without a separate engagement platform.',
    pros: ['Native to Salesforce — fully unified data.', 'Prioritized work queues for reps.', 'No third-party sync to maintain.'],
    cons: ['Requires Salesforce and the right edition/licenses.', 'Less specialized than best-of-breed engagement tools.', 'Admin and setup overhead.'],
    pricing: 'Licensed as part of Salesforce Sales Cloud editions/add-ons. Contact vendor.',
    community: 'Practitioners value native cadences for Salesforce shops, weighing them against best-of-breed tools like Outreach and Salesloft. Puetto synthesis — verify against the sources below.',
    features: {"multichannel":"yes","warmup":"no","builtInData":"no","unlimitedMailboxes":"no","crmSync":"yes"},
    priceFrom: 'Salesforce add-on',
    bestForTag: 'Salesforce shops',
    alternatives: ['outreach', 'salesloft', 'hubspot-sequences'],
    sourceLinks: [{ label: 'Salesforce Sales Engagement on G2', url: 'https://www.g2.com/products/salesforce-sales-engagement/reviews' }],
  },
  {
    slug: 'lavender',
    name: 'Lavender',
    category: 'email-automation',
    website: 'https://www.lavender.ai',
    oneLiner: 'AI email coach that scores and improves outbound emails in real time as you write.',
    whatItDoes: 'Lavender is an AI email-writing assistant that scores emails for clarity, length, and likelihood of a reply, and suggests improvements inside the inbox or sequencing tool as a rep writes. It also surfaces recipient context. It is not a sender; it improves the messages your other tools send. In ABM, where reply quality on personalized touches matters more than volume, it raises the standard of each email.',
    bestFor: 'Sales teams that want to lift reply rates by coaching reps on email quality, used alongside a sender.',
    pros: ['Real-time email scoring and rewrite suggestions.', 'Works inside Gmail, Outlook, and many sequencers.', 'Improves quality without changing your sending stack.'],
    cons: ['A coaching layer, not a sender.', 'Value depends on reps actually applying suggestions.', 'Per-seat cost on top of your sending tool.'],
    pricing: 'Per-seat tiers, with a limited free option. Verify on the vendor site.',
    community: 'Practitioners cite Lavender for improving reply rates and coaching newer reps, with the caveat that it complements rather than replaces a sender. Puetto synthesis — verify against the sources below.',
    features: {"multichannel":"no","warmup":"no","builtInData":"no","unlimitedMailboxes":"no","crmSync":"limited"},
    priceFrom: 'Free / from ~$29/seat',
    bestForTag: 'Email coaching',
    alternatives: ['lemlist', 'amplemarket', 'clay-outbound'],
    sourceLinks: [{ label: 'Lavender on G2', url: 'https://www.g2.com/products/lavender/reviews' }],
  },
];

// Comparison-table columns for the email-automation category.
export const EMAIL_FEATURE_COLUMNS = [
  { key: 'multichannel',       label: 'Multichannel' },
  { key: 'warmup',             label: 'Warmup / Deliverability' },
  { key: 'builtInData',        label: 'Built-in Data' },
  { key: 'unlimitedMailboxes', label: 'Unlimited Mailboxes' },
  { key: 'crmSync',            label: 'CRM Sync' },
];

// -----------------------------------------------------------------------------
// Helpers — used by the page components
// -----------------------------------------------------------------------------
export const getCategory = (slug) => CATEGORIES.find((c) => c.slug === slug);
export const getTool = (slug) => TOOLS.find((t) => t.slug === slug);
export const getToolsInCategory = (catSlug) =>
  TOOLS.filter((t) => t.category === catSlug);
export const getAlternatives = (tool) =>
  (tool.alternatives || []).map((s) => getTool(s)).filter(Boolean);
export const getCategoryForTool = (tool) => getCategory(tool.category);

// Flat list of route paths for the sitemap (add these to vite.config.js routes).
export const ALL_TOOL_LIBRARY_ROUTES = [
  '/abm-ops/tools',
  ...CATEGORIES.map((c) => `/abm-ops/tools/${c.slug}`),
  ...TOOLS.map((t) => `/abm-ops/tools/${t.category}/${t.slug}`),
];
